//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DboTicariOtomasyonEntities1 : DbContext
    {
        public DboTicariOtomasyonEntities1()
            : base("name=DboTicariOtomasyonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Notlar> Tbl_Notlar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Bankalar> Tbl_Bankalar { get; set; }
        public virtual DbSet<Tbl_FirmaHareketler> Tbl_FirmaHareketler { get; set; }
        public virtual DbSet<Tbl_Giderler> Tbl_Giderler { get; set; }
        public virtual DbSet<Tbl_Ilceler> Tbl_Ilceler { get; set; }
        public virtual DbSet<Tbl_Kodlar> Tbl_Kodlar { get; set; }
        public virtual DbSet<Tbl_MusteriHareketler> Tbl_MusteriHareketler { get; set; }
        public virtual DbSet<Tbl_Musteriler> Tbl_Musteriler { get; set; }
        public virtual DbSet<Tbl_Personeller> Tbl_Personeller { get; set; }
        public virtual DbSet<Tbl_Sehirler> Tbl_Sehirler { get; set; }
        public virtual DbSet<Tbl_Sirketler> Tbl_Sirketler { get; set; }
        public virtual DbSet<Tbl_Stoklar> Tbl_Stoklar { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_AltKategoriler> Tbl_AltKategoriler { get; set; }
        public virtual DbSet<Tbl_Kategoriler> Tbl_Kategoriler { get; set; }
        public virtual DbSet<Tbl_FaturaBilgi> Tbl_FaturaBilgi { get; set; }
        public virtual DbSet<Tbl_FaturaDetay> Tbl_FaturaDetay { get; set; }
        public virtual DbSet<Tbl_Urunler> Tbl_Urunler { get; set; }
        public virtual DbSet<Tbl_UrunLoglari> Tbl_UrunLoglari { get; set; }
        public virtual DbSet<Tbl_Izinler> Tbl_Izinler { get; set; }
        public virtual DbSet<Tbl_Rol_Izinleri> Tbl_Rol_Izinleri { get; set; }
        public virtual DbSet<Tbl_Roller> Tbl_Roller { get; set; }
        public virtual DbSet<Tbl_AdminRules> Tbl_AdminRules { get; set; }
        public virtual DbSet<vw_SatisHareketleri> vw_SatisHareketleri { get; set; }
        public virtual DbSet<vw_KategoriSatisOzet> vw_KategoriSatisOzet { get; set; }
        public virtual DbSet<vw_PersonelSatisOzet> vw_PersonelSatisOzet { get; set; }
        public virtual DbSet<vw_UrunSatisOzet> vw_UrunSatisOzet { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<PrcFirmaHareketler_Result> PrcFirmaHareketler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrcFirmaHareketler_Result>("PrcFirmaHareketler");
        }
    
        public virtual ObjectResult<PrcMusteriHareketler_Result> PrcMusteriHareketler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrcMusteriHareketler_Result>("PrcMusteriHareketler");
        }
    }
}
