//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FaturaDetay
    {
        public int FaturaDetayID { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string FaturaDetayUrunAd { get; set; }
        public Nullable<short> FaturaDetayMiktar { get; set; }
        public Nullable<decimal> FaturaDetayFiyat { get; set; }
        public Nullable<decimal> FaturaDetayTutar { get; set; }
    
        public virtual Tbl_FaturaBilgi Tbl_FaturaBilgi { get; set; }
    }
}
