//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Giderler
    {
        public int GiderId { get; set; }
        public string GiderAy { get; set; }
        public string GiderYıl { get; set; }
        public Nullable<decimal> GiderElektrik { get; set; }
        public Nullable<decimal> GiderSu { get; set; }
        public Nullable<decimal> GiderDogalgaz { get; set; }
        public Nullable<decimal> GiderInternet { get; set; }
        public Nullable<decimal> GiderMaaslar { get; set; }
        public Nullable<decimal> GiderEkstra { get; set; }
        public string GiderNotlar { get; set; }
    }
}
