//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FaturaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FaturaBilgi()
        {
            this.Tbl_FaturaDetay = new HashSet<Tbl_FaturaDetay>();
        }
    
        public int FaturaID { get; set; }
        public string FaturaTipi { get; set; }
        public string FaturaNo { get; set; }
        public string FaturaTarih { get; set; }
        public string FaturaSaat { get; set; }
        public string FaturaVergiDaire { get; set; }
        public string FaturaSatıcı { get; set; }
        public string FaturaAlıcı { get; set; }
        public string FaturaAlıcıAdres { get; set; }
        public string FaturaAlıcıTelefon { get; set; }
        public string FaturaAlıcıEPosta { get; set; }
        public string FaturaAlıcıVergiDaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FaturaDetay> Tbl_FaturaDetay { get; set; }
    }
}
