//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urunler()
        {
            this.Tbl_FirmaHareketler = new HashSet<Tbl_FirmaHareketler>();
            this.Tbl_MusteriHareketler = new HashSet<Tbl_MusteriHareketler>();
        }
    
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string UrunMarka { get; set; }
        public string UrunModel { get; set; }
        public string UrunYil { get; set; }
        public Nullable<short> UrunAdet { get; set; }
        public Nullable<decimal> UrunAlisFiyat { get; set; }
        public Nullable<decimal> UrunSatisFiyat { get; set; }
        public string UrunDetay { get; set; }
        public Nullable<int> AltKategoriID { get; set; }
    
        public virtual Tbl_AltKategoriler Tbl_AltKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FirmaHareketler> Tbl_FirmaHareketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MusteriHareketler> Tbl_MusteriHareketler { get; set; }
    }
}
