//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notlar
    {
        public int NotID { get; set; }
        public string NotTarih { get; set; }
        public string NotSaat { get; set; }
        public string NotBaslik { get; set; }
        public string NotDetay { get; set; }
        public string NotOlusturan { get; set; }
        public string NotHitap { get; set; }
    }
}
