//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musteriler()
        {
            this.Tbl_MusteriHareketler = new HashSet<Tbl_MusteriHareketler>();
        }
    
        public int MusteriID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriTelefon2 { get; set; }
        public string MusteriTC { get; set; }
        public string MusteriMail { get; set; }
        public string MusteriSehir { get; set; }
        public string MusteriIlce { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriVergiDaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MusteriHareketler> Tbl_MusteriHareketler { get; set; }
    }
}
