//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ilceler
    {
        public string IlceId { get; set; }
        public string IlceAdi { get; set; }
        public int SehirId { get; set; }
    
        public virtual Tbl_Sehirler Tbl_Sehirler { get; set; }
    }
}
