//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bankalar
    {
        public int BankaId { get; set; }
        public string BankaAdi { get; set; }
        public string BankaSehir { get; set; }
        public string BankaIlce { get; set; }
        public string BankaSube { get; set; }
        public string BankaIBAN { get; set; }
        public string BankaHesapNo { get; set; }
        public string BankaYetkili { get; set; }
        public string BankaTelefon { get; set; }
        public Nullable<System.DateTime> BankaTarih { get; set; }
        public string BankaHesapTuru { get; set; }
        public Nullable<int> SirketID { get; set; }
    
        public virtual Tbl_Sirketler Tbl_Sirketler { get; set; }
    }
}
