//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rol_Izinleri
    {
        public int Rol_IzinleriId { get; set; }
        public int RolId { get; set; }
        public int IzinId { get; set; }
    
        public virtual Tbl_Izinler Tbl_Izinler { get; set; }
        public virtual Tbl_Roller Tbl_Roller { get; set; }
    }
}
