//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sirketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sirketler()
        {
            this.Tbl_Bankalar = new HashSet<Tbl_Bankalar>();
            this.Tbl_FirmaHareketler = new HashSet<Tbl_FirmaHareketler>();
        }
    
        public int SirketID { get; set; }
        public string SirketAd { get; set; }
        public string YetkiliStatu { get; set; }
        public string YetkiliAdSoyad { get; set; }
        public string YetkiliTC { get; set; }
        public string SirketSektor { get; set; }
        public string SirketTelefon1 { get; set; }
        public string SirketTelefon2 { get; set; }
        public string SirketTelefon3 { get; set; }
        public string SirketMail { get; set; }
        public string SirketFax { get; set; }
        public string SirketSehir { get; set; }
        public string SirketIlce { get; set; }
        public string SirketVergiDaire { get; set; }
        public string SirketAdres { get; set; }
        public string OzelKod1 { get; set; }
        public string OzelKod2 { get; set; }
        public string OzelKod3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Bankalar> Tbl_Bankalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FirmaHareketler> Tbl_FirmaHareketler { get; set; }
    }
}
