//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MusteriHareketler
    {
        public int MusteriHareketID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public string Tarih { get; set; }
        public string Notlar { get; set; }
    
        public virtual Tbl_Musteriler Tbl_Musteriler { get; set; }
        public virtual Tbl_Personeller Tbl_Personeller { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
