//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personeller()
        {
            this.Tbl_FirmaHareketler = new HashSet<Tbl_FirmaHareketler>();
            this.Tbl_MusteriHareketler = new HashSet<Tbl_MusteriHareketler>();
        }
    
        public int PersonellD { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelTC { get; set; }
        public string PersonelSehir { get; set; }
        public string Personellce { get; set; }
        public string PersonelAdres { get; set; }
        public string PersonelGorev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FirmaHareketler> Tbl_FirmaHareketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MusteriHareketler> Tbl_MusteriHareketler { get; set; }
    }
}
