//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AdminRules
    {
        public int AdminRoleId { get; set; }
        public int AdminID { get; set; }
        public int RolId { get; set; }
    
        public virtual Tbl_Admin Tbl_Admin { get; set; }
        public virtual Tbl_Roller Tbl_Roller { get; set; }
    }
}
