//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UrunLoglari
    {
        public int LogId { get; set; }
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunMarka { get; set; }
        public string IslemTipi { get; set; }
        public string EskiDeger { get; set; }
        public string YeniDeger { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string Kullanici { get; set; }
    }
}
