//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KategoriSatisOzet
    {
        public int KategoriID { get; set; }
        public string KategoriAdi { get; set; }
        public Nullable<int> UrunSayisi { get; set; }
        public Nullable<int> ToplamAdet { get; set; }
        public Nullable<decimal> ToplamCiro { get; set; }
    }
}
